development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "a698af0a927321e7479611c432e213f1b32bd8e999aaffad678de9371723d513"
  signature_expiration: 3600 # one hour
