module AddressHelper

	def in_states
		[
			['Andhra Pradesh'],
			['Arunachal Pradesh'],
			['Assam'],
			['Bihar'],
			['Chhattisgarh'],
			['Goa'],
			['Gujarat'],
			['Haryana'],
			['Himachal Pradesh'],		
			['Jammu & Kashmir'],
			['Jharkhand'],
			['Karnataka'],
			['Kerala'],
			['Madhya Pradesh'],
			['Maharashtra'],
			['Manipur'],
			['Meghalaya'],
			['Mizoram'],
			['Nagaland'],
			['Odisha'],
			['Punjab'],
			['Rajasthan'],
			['Sikkim'],
			['Tamil Nadu'],
			['Tripura'],
			['Uttarakhand'],
			['Uttar Pradesh'],
			['West Bengal'],
			['Andaman & Nicobar'],
			['Chandigarh'],
			['Dadra and Nagar Haveli'],
			['Daman & Diu'],
			['Delhi'],
			['Lakshadweep'],
			['Puducherry'],
			#['Andhra Pradesh','AP'],
			#['Arunachal Pradesh','AR'],
			#['Assam','AS'],
			#['Bihar','BR'],
			#['Chhattisgarh','CT'],
			#['Goa','GA'],
			#['Gujarat','GJ'],
			#['Haryana','HR'],
			#['Himachal Pradesh','HP'],
			#['Jammu & Kashmir','JK'],
			#['Jharkhand','JH'],
			#['Karnataka','KA'],
			#['Kerala','KL'],
			#['Madhya Pradesh','MP'],
			#['Maharashtra','MH'],
			#['Manipur','MN'],
			#['Meghalaya','ML'],
			#['Mizoram','MZ'],
			#['Nagaland','NL'],
			#['Odisha','OR'],
			#['Punjab','PB'],
			#['Rajasthan','RJ'],
			#['Sikkim','SK'],
			#['Tamil Nadu','TN'],
			#['Tripura','TR'],
			#['Uttarakhand','UK'],
			#['Uttar Pradesh','UP'],
			#['West Bengal','WB'],
			#['Andaman & Nicobar','AN'],
			#['Chandigarh','CH'],
			#['Dadra and Nagar Haveli','DN'],
			#['Daman & Diu','DD'],
			#['Delhi','DL'],
			#['Lakshadweep','LD'],
			#['Puducherry','PY'],
		]
	end

end